- CONTRIBUTE.md
- README.md
add a CONTRIBUTE guide in order to open this project to the world
update README including real status of this app
Signed-off-by: Paco Orozco <paco@pacoorozco.info>
> doc: add contribute guide and update README

- app/Http/Controllers/QuestionController.php
- resources/lang/en/question/messages.php
- resources/views/question/show-answered.blade.php
- resources/views/question/show.blade.php
Solve issue #7 - User: Can't answer questions.
When a user answer a question, a new view show information about its answer.
Closes #7
Signed-off-by: Paco Orozco <paco@pacoorozco.info>
> fix: solve issue #7 - User: Can't answer questions.

- README.md
- docker-compose.yml
- docker/app/Dockerfile
- docker/app/laravel.ini
- docker/web/Dockerfile
- docker/web/nginx.conf
- docker/web/sites/default.conf
Add docker stack to run this application using `docker-compose`. `README.md` has been updated.
> Add docker stack to run gamify [skip ci]

- .env.travis
- .gitignore
- .scrutinizer.yml
- .styleci.yml
- .symfony.insight.yaml
- .travis.yml
- CODE_OF_CONDUCT.md
I've configured every CI/CD phase to use PHP 7.2. I've removed some useless errrors also.
> Optimize CI/CD pipeline to be faster

- CHANGELOG.md
- docker/web/Dockerfile
**What issue type does this pull request address?** (keep at least one, remove the others)  
/kind bug
resolves #61
> Fix Docker build

- CHANGELOG.md
- resources/views/admin/badge/_form.blade.php
- resources/views/admin/badge/index.blade.php
- resources/views/admin/level/_form.blade.php
- resources/views/admin/level/index.blade.php
- resources/views/admin/question/_form.blade.php
- resources/views/admin/question/index.blade.php
- resources/views/admin/reward/index.blade.php
- resources/views/admin/user/index.blade.php
- resources/views/auth/login.blade.php
- resources/views/layouts/admin.blade.php
- resources/views/profile/_settings.blade.php
- webpack.mix.js
Change the HTML editor to [Bootstrap-wysihtml5](https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg).
resolves #36 
The HTML is slightly different, now it's [Bootstrap-wysihtml5](https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg). We have reduced the load of the page by ~125K.
[Bootstrap-wysihtml5](https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg) was already part of AdminLTE.
> Chage editor to bootstrap-wysiwyg5

- CHANGELOG.md
- app/Http/Controllers/Admin/AdminLevelController.php
- app/Http/Requests/LevelCreateRequest.php
- app/Http/Requests/LevelUpdateRequest.php
- app/Level.php
- resources/lang/en/admin/level/title.php
- resources/views/admin/level/_details.blade.php
- resources/views/admin/level/create.blade.php
- resources/views/admin/level/edit.blade.php
- resources/views/admin/level/index.blade.php
- tests/Feature/Models/LevelTest.php
- tests/Unit/LevelTest.php
/kind feature
resolves #96 
**Does this pull request has user-facing changes?**
Allows admins to manage images associated to Level
> Add image management to Level

- .env.example
- CHANGELOG.md
- composer.json
- composer.lock
Add AWS s3 support for image uploading.
> Add S3 support

- .gitignore
- CHANGELOG.md
- config/view.php
- resources/views/custom/.gitignore
> Allow customized views

- .env.example
- composer.json
- composer.lock
- config/database.php
- config/session.php
- docker-compose.yml
/kind feature
resolves #103
No
**Does this pull request add new dependencies?** 
Yes, `predis/predis`.
> Add support for Redis and move cache & session

- .github/workflows/01-release-version.yml
- .gitignore
- CHANGELOG.md
- composer.json
Add a release action to publish distribution files properly
> Add release workflow

- .github/workflows/main.yml
**What issue type does this pull request address?** (keep at least one, remove the others)  
/kind bug
/kind feature
/kind documentation
resolves #
**What else do we need to know?**
> Fix github action

- .github/workflows/main.yml
**What issue type does this pull request address?** (keep at least one, remove the others)  
/kind bug
/kind feature
/kind documentation
resolves #
**What else do we need to know?**
> Fix github action 2

- .github/workflows/main.yml
> Fix asset name on release

- .env.example
- CHANGELOG.md
- config/trustedproxy.php
- routes/api.php
> Small fixes

- CHANGELOG.md
- app/Http/Controllers/Admin/AdminUserController.php
> Fix issue #117

- CHANGELOG.md
- app/Http/Controllers/QuestionController.php
- app/Http/View/Composers/UserSidebarComposer.php
- app/Providers/ViewServiceProvider.php
/kind bug
resolves #121 
**Does this pull request has user-facing changes?**
No
I've created a view composer to `partials.sidebar`.
> Add a view composer for partials.sidebar

- CHANGELOG.md
- resources/lang/en/admin/question/model.php
/kind bug
resolves #124 
Question name is public. So authors should not use this name to leak any solution.
> Fix issue 124

- CHANGELOG.md
- app/Http/Controllers/Admin/AdminQuestionController.php
- app/Question.php
- resources/lang/en/admin/question/model.php
- resources/lang/en/general.php
- resources/views/admin/question/_details.blade.php
- resources/views/admin/question/_form.blade.php
- resources/views/admin/question/index.blade.php
- resources/views/admin/question/partials/_add_status_and_visibility_labels.blade.php
- resources/views/admin/question/partials/_question_name_with_link.blade.php
- resources/views/admin/question/partials/_question_type.blade.php
**What issue type does this pull request address?**
/kind bug
resolves #120 
Added link to questions
> Implement links for questions

- CHANGELOG.md
- app/Http/Controllers/QuestionController.php
- app/User.php
- resources/views/question/_answered_questions_box.blade.php
- resources/views/question/_next_level_box.blade.php
- resources/views/question/index.blade.php
> Add user metrics

- CHANGELOG.md
- app/Badge.php
- app/Http/Controllers/Admin/AdminBadgeController.php
- app/Http/Controllers/Admin/AdminDashboardController.php
- app/Http/Controllers/Admin/AdminQuestionController.php
- app/Http/Middleware/OnlyAjax.php
- app/Http/Requests/QuestionCreateRequest.php
- app/Question.php
- app/User.php
- database/factories/LevelFactory.php
- database/factories/Question.php
- database/factories/UserFactory.php
- resources/lang/en/admin/question/model.php
- resources/lang/en/admin/user/model.php
- resources/lang/en/validation.php
- resources/views/admin/dashboard/_info_boxes.blade.php
- resources/views/admin/dashboard/_latest_published_questions.blade.php
- resources/views/admin/dashboard/_latest_registered_users.blade.php
- resources/views/admin/dashboard/index.blade.php
- resources/views/admin/question/_form.blade.php
- resources/views/admin/question/create.blade.php
- tests/Feature/Http/Controllers/Admin/AdminBadgeControllerTest.php
- tests/Feature/Http/Controllers/Admin/AdminDashboardControllerTest.php
- tests/Feature/Http/Controllers/Admin/AdminLevelControllerTest.php
- tests/Feature/Http/Controllers/Admin/AdminQuestionControllerTest.php
- tests/Feature/Http/Controllers/Admin/AdminUserControllerTest.php
- tests/TestCase.php
> Add BadgeController tests

- .scrutinizer.yml
- .symfony.insight.yaml
- .travis.yml
- CHANGELOG.md
- composer.json
- composer.lock
- docker/app/Dockerfile
Some of the future work needs an updated version of PHP, so this PR is updating the PHP minimum version to 7.4
> Update php version

- app/Http/Controllers/Admin/AdminQuestionController.php
- app/Presenters/QuestionPresenter.php
- app/Question.php
> Fix scrutinizer

- .env.example
- CHANGELOG.md
- app/Badge.php
- app/Http/Controllers/Admin/AdminBadgeController.php
- app/Presenters/BadgePresenter.php
- app/Presenters/QuestionPresenter.php
- app/Question.php
- resources/views/admin/badge/_details.blade.php
- resources/views/admin/badge/_form.blade.php
- resources/views/profile/_overview.blade.php
- tests/Feature/Models/BadgeTest.php
- resolves #162 
Default configuration has been changed on `.env.example`. 
You should comment `UPLOAD_DISK` or set it to `UPLOAD_DISK=public`. 
If you set it to `UPLOAD_DISK=` it will not work properly.
No
> Fix badge images not shown

- app/Presenters/BadgePresenter.php
> Fix badge images

- CHANGELOG.md
- app/Http/Controllers/Admin/AdminQuestionController.php
> Fix issue 177

- CONTRIBUTE.md
**What issue type does this pull request address?** (choose at least one)
> Update contribute documentation

- CHANGELOG.md
- app/Enums/QuestionActuators.php
- app/Http/Controllers/Admin/AdminQuestionActionController.php
- app/Http/Requests/QuestionActionCreateRequest.php
- app/Models/QuestionAction.php
- resources/lang/en/enums.php
- resources/lang/vendor/laravelEnum/en/messages.php
- resources/views/admin/action/_form.blade.php
- resources/views/admin/question/edit.blade.php
- tests/Unit/Models/QuestionActionTest.php
> Fix error when adding actions to questions

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
> Fix typos in Pull Request and Bug report template

- CHANGELOG.md
- routes/web.php
- resolves #193 
Yes, make the link work.
No
> Fix Rewards link on sidebar

- CHANGELOG.md
- resources/views/admin/dashboard/_latest_published_questions.blade.php
> Fix missing translation 'admin/question/model.published_at'

- CHANGELOG.md
- app/Http/Controllers/Auth/ChangePasswordController.php
- resources/lang/en/auth.php
- resources/lang/en/passwords.php
- resources/lang/en/user/profile.php
- resources/views/auth/change_password.blade.php
- resources/views/profile/show.blade.php
- routes/web.php
- tests/Feature/Http/Controllers/Auth/ChangePasswordControllerTest.php
- bug
- resolves #135 
Yes, It allows users to change their passwords
No
> Issue 135: Users were not able to change their passwords

- .scrutinizer.yml
- .travis.yml
- CHANGELOG.md
- README.md
- app/Models/Question.php
- composer.json
- composer.lock
- docker/app/Dockerfile
> Change PHP version in CI to PHP 8

- .env.example
- CHANGELOG.md
- database/migrations/2021_04_15_150211_create_sessions_table.php
- resources/views/custom/.gitignore
- feature
- resolves #204 
No
No
> Change session storage to database

- app/Console/Commands/PublishScheduledQuestions.php
- app/Console/Kernel.php
- app/Models/Question.php
- tests/Feature/Http/Console/Commands/PublishScheduledQuestionsTest.php
- tests/Feature/Models/QuestionTest.php
- bug
- resolves #203 
Yes, It adds a new command `gamify:publish` to publish scheduled questions. This command is executed every hour.
No
> Add artisan command to publish scheduled questions

- CHANGELOG.md
- app/Http/Controllers/Admin/AdminUserController.php
- app/Providers/AuthServiceProvider.php
- resources/views/admin/user/_form.blade.php
- tests/Feature/Http/Controllers/Admin/AdminUserControllerTest.php
- bug
- resolves #194
Yes, It disallows users to change its own role
> Add restriction to update user's own role

- CHANGELOG.md
- resources/views/admin/partials/footer.blade.php
- resources/views/admin/partials/header.blade.php
- resources/views/layouts/login.blade.php
- resources/views/layouts/master.blade.php
- resources/views/partials/footer.blade.php
- resources/views/partials/header.blade.php
- feature
- resolves #191 
No
No
> Add specific version number on admin section's footer

- .github/dependabot.yml
- .github/workflows/release-version.yml
- .github/workflows/run-tests.yml
> Update GitHub actions

- app/Http/Controllers/Admin/AdminDashboardController.php
- app/Libs/Game/Game.php
- app/Models/User.php
- resources/views/admin/dashboard/_info_boxes.blade.php
- tests/Feature/Http/Controllers/Admin/AdminDashboardControllerTest.php
- tests/Feature/Listeners/IncrementBadgeOnQuestionAnsweredTest.php
- tests/Feature/Listeners/IncrementBadgeOnUserLoginTest.php
> Refactor users

- app/Http/Controllers/Admin/AdminRewardController.php
- app/Http/Controllers/HomeController.php
- app/Http/Requests/RewardBadgeRequest.php
- app/Http/Requests/RewardExperienceRequest.php
- app/Libs/Game/Game.php
- app/Listeners/AddAchievements.php
- app/Listeners/AddReputation.php
- app/Listeners/IncrementBadgesOnQuestionAnswered.php
- app/Listeners/IncrementBadgesOnUserLogin.php
- app/Listeners/UpdateExperience.php
- app/Models/User.php
- tests/Feature/Libs/Game/GameTest.php
- tests/Feature/Models/UserTest.php
> Refactor rewards to improve readability

- CHANGELOG.md
- app/Http/Controllers/Admin/AdminQuestionController.php
- app/Http/Controllers/UserController.php
- app/Http/Requests/QuestionCreateRequest.php
- app/Http/Requests/QuestionUpdateRequest.php
- app/Models/Badge.php
- app/Models/Level.php
- database/factories/BadgeFactory.php
- resources/views/admin/level/edit.blade.php
- resources/views/profile/show.blade.php
- tests/Feature/Http/Controllers/UserControllerTest.php
- tests/Feature/Models/BadgeTest.php
- enhancement
Small changes removing unused code and adding missing tests
> Refactor user controller

- tests/Feature/Http/Controllers/Admin/AdminRewardControllerTest.php
- bug
- Remove dumpSession() from a test
> Remove dumpSession() in a test

- app/Http/Controllers/QuestionController.php
- resources/views/partials/user_dropdown.blade.php
> Fix logout button

- CHANGELOG.md
- app/Http/Controllers/Admin/AdminUserController.php
- app/Http/Requests/UserCreateRequest.php
- app/Http/Requests/UserUpdateRequest.php
- resources/views/admin/user/_form.blade.php
- tests/Feature/Http/Controllers/Admin/AdminUserControllerTest.php
> Remove passwords fields from admin's user creation/modification forms

- app/View/Components/Tags/FormSelectTags.php
- resources/views/admin/question/create.blade.php
- resources/views/admin/question/edit.blade.php
- resources/views/components/tags/form-select-tags.blade.php
- tests/Unit/Views/Components/Tags/FormSelectTagsTest.php
> Fix issue 6

- README.md
Found a small typo (user credentials - [UserSeeder.php#L42](https://github.com/pacoorozco/gamify-laravel/blob/71a76e539632bdf54fddcd4a0dffc22ec36a5abe/database/seeders/UserSeeder.php#L42)) in README .
> [info] fix user credentials (src: database/seeders/UserSeeder.php)

- HOWTO.md
- resources/views/custom/.gitignore
- enhancement
- related to #307 
Just add documentation
> Issue 307: Add documentation about how to use custom views

- app/Http/Controllers/LeaderBoardController.php
- app/Libs/Game/Game.php
- resources/views/leaderboard/index.blade.php
- resources/views/partials/header.blade.php
- resources/views/partials/sidebar.blade.php
- routes/web.php
- tests/Feature/Http/Controllers/LeaderBoardControllerTest.php
- feature
- resolves #324 
Yes, it allow guests users to see the leader board
> Implement a leaderboard system for guests

- app/Models/User.php
- app/Services/SocialAccountService.php
- app/Services/UsernameGeneratorService.php
- tests/Feature/Models/UserTest.php
- tests/Feature/Services/UsernameGeneratorServiceTest.php
> Fix issue 336

- app/Actions/UpdateUserProfileAction.php
- app/Http/Requests/ProfileUpdateRequest.php
- lang/en/user/profile.php
- resources/views/account/profile/edit.blade.php
- routes/web.php
- tests/Feature/Http/Controllers/Account/ProfileControllerTest.php
> Fix issue 338

- app/Presenters/QuestionPresenter.php
- resources/views/admin/question/edit.blade.php
- resources/views/admin/question/show.blade.php
- tests/Feature/Presenters/QuestionPresenterTest.php
> Fix creator and updater attributes with presenter

- resources/views/admin/dashboard/_latest_published_questions.blade.php
- resources/views/admin/dashboard/_next_scheduled_questions.blade.php
> Add warning messages when no published or scheduled questions

- app/Http/Controllers/HomeController.php
- app/Http/Controllers/QuestionController.php
- app/Models/Question.php
- app/Models/User.php
- database/factories/QuestionFactory.php
- tests/Feature/Models/QuestionTest.php
- tests/Feature/Models/UserTest.php
> Refactor available questions

- app/Http/Controllers/Admin/AdminBadgeDataTablesController.php
- app/Http/Controllers/Admin/AdminQuestionDataTablesController.php
- app/Presenters/BadgePresenter.php
- resources/views/admin/badge/index.blade.php
- resources/views/admin/question/index.blade.php
- resources/views/question/index.blade.php
- tests/Feature/Http/Controllers/Admin/AdminBadgeDataTablesControllerTest.php
- tests/Feature/Http/Controllers/Admin/AdminQuestionDataTablesControllerTest.php
> Add tags to Question's & Badge's indexes

- .env.example
- lang/en/site.php
- resources/views/admin/partials/header.blade.php
- resources/views/layouts/admin.blade.php
- resources/views/layouts/login.blade.php
- resources/views/layouts/master.blade.php
- resources/views/partials/header.blade.php
> Allows to configure site name from config app.name

- lang/en/user/profile.php
- resources/views/profile/_badge_unlocked.blade.php
- resources/views/profile/_overview.blade.php
> Stylish badge's modals to see details of the badge

- app/Http/Controllers/MarkNotificationAsReadController.php
- app/Libs/Game/Game.php
- app/Models/User.php
- app/Notifications/BadgeUnlocked.php
- database/migrations/2022_10_11_150317_create_notifications_table.php
- lang/en/notifications.php
- resources/views/account/password/index.blade.php
- resources/views/layouts/master.blade.php
- resources/views/partials/notifications.blade.php
- resources/views/partials/sidebar.blade.php
- resources/views/profile/show.blade.php
- routes/web.php
- tests/Feature/Http/Controllers/MarkNotificationAsReadControllerTest.php
> Implement notifications for unlocked badges

- app/Models/Level.php
- app/Models/User.php
- app/Observers/LevelObserver.php
- app/Providers/AppServiceProvider.php
- database/migrations/2015_12_10_143950_create_levels_table.php
- lang/en/question/messages.php
- resources/views/question/_empty-list.blade.php
> Increase performance by reducing # of queries

- app/Http/Controllers/HomeController.php
- routes/web.php
- enhancement
Takes advantage of Laravel 9's new methods
> Use new Route::controller() method

- composer.json
- composer.lock
- enhancement
- resolves #413
- resolves #414 
- resolves #415 
- resolves #416 
- resolves #417 
- resolves #418 
No
No
> update dependencies to latest versions

- CHANGELOG.md
- app/Events/SocialLogin.php
- app/Http/Controllers/Auth/SocialAccountController.php
- app/Providers/EventServiceProvider.php
- tests/Feature/Auth/AuthenticationTest.php
- tests/Feature/Auth/SocialAuthenticationTest.php
- tests/Feature/Listeners/IncrementBadgeOnUserLoginTest.php
> Fix the lack of events when login with Social Account

- phpunit.xml
- tests/Feature/TestCase.php
- bug
- Tests were passing on clean environment, but due to `DatabaseTransactions` the tests were failing after several unclear runs. With `RefreshDatabase` trait is more sustainable (and the recommended way by Laravel).
> Replace DatabaseTransactions by RefreshDatabase trait

- app/Http/Controllers/Admin/AdminQuestionDataTablesController.php
- app/Presenters/BadgePresenter.php
- app/Presenters/LevelPresenter.php
- resources/views/admin/badge/edit.blade.php
- resources/views/admin/badge/show.blade.php
- resources/views/admin/level/edit.blade.php
- resources/views/admin/level/show.blade.php
- resources/views/admin/question/edit.blade.php
- resources/views/admin/question/show.blade.php
- resources/views/admin/user/edit.blade.php
- resources/views/admin/user/show.blade.php
- bug
- After replacing the Presenter class, some fields were not present on the views.
> Fix bug of missing published fields

- app/Http/Requests/RewardExperienceRequest.php
- app/Libs/Game/Game.php
- tests/Feature/Http/Controllers/Admin/AdminRewardControllerTest.php
> Fix small bugs

- phpstan.neon
- bug
- enhancement
- feature
- documentation
- resolves #
> Fix typo in PHPstan

- docker-compose.yml
After upgrading the minimum version to PHP 8.2 I forgot to change it in Sail
- bug
> Update Sail to PHP 8.2

- tests/Unit/Components/Forms/InputTest.php
> Add test cases to input component

- .github/workflows/jekyll-gh-pages.yml
- README.md
- docs/index.md
> Add documentation

- README.md
- docs/_config.yml
- docs/index.md
> Fix documentation
